// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAgil.API.Data;

namespace ProAgil.API.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20191020182529_init")]
  partial class init
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.0");

      modelBuilder.Entity("ProAgil.API.Models.Event", b =>
          {
            b.Property<int>("EventId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<string>("Date")
                      .HasColumnType("TEXT");

            b.Property<string>("Local")
                      .HasColumnType("TEXT");

            b.Property<string>("Lot")
                      .HasColumnType("TEXT");

            b.Property<int>("PeopleCount")
                      .HasColumnType("INTEGER");

            b.Property<string>("Theme")
                      .HasColumnType("TEXT");

            b.HasKey("EventId");

            b.ToTable("Events");
          });
#pragma warning restore 612, 618
    }
  }
}
